<?php namespace App\Database\Seeds;

class PermissionClinicSeeder extends \CodeIgniter\Database\Seeder
{
        public $table = 'permissions';

        public function run()
        {
                $data = [
                  [
                     'function_name' => 'show dentist details',
                     'function_description' => 'show dentist details',
                     'slugs' => 'show-dentist',
                     'name_on_class' => 'show_dentist',
                     'page_title' => 'dentist details',
                     'module_id' => '4',
                      'link_icon' => '',
                     'order' => '101',
                     'table_name' => 'dentists',
                     'func_action' => 'show',
                     'func_type' => 3,
                     'allowed_roles' => "[1]",
                     'status' => 'a',
                     'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'create dentist',
                      'function_description' => 'create dentist',
                      'slugs' => 'add-dentist',
                      'name_on_class' => 'add_dentist',
                      'page_title' => 'create a dentist',
                      'module_id' => '4',
                      'link_icon' => '',
                      'order' => '102',
                      'table_name' => 'dentists',
                      'func_action' => 'add',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'list of dentist',
                      'function_description' => 'list of dentist',
                      'slugs' => 'list-dentist',
                      'name_on_class' => 'index',
                      'page_title' => 'list of dentists',
                      'module_id' => '4',
                      'link_icon' => '<i class="fas fa-users"></i>',
                      'order' => '103',
                      'table_name' => 'dentists',
                      'func_action' => 'link',
                      'func_type' => 1,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'edit dentist',
                      'function_description' => 'edit dentist',
                      'slugs' => 'edit-dentist',
                      'name_on_class' => 'edit_dentist',
                      'page_title' => 'edit dentist',
                      'module_id' => '4',
                      'link_icon' => '',
                      'order' => '104',
                      'table_name' => 'dentists',
                      'func_action' => 'edit',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'delete dentist',
                      'function_description' => 'delete dentist',
                      'slugs' => 'delete-dentist',
                      'name_on_class' => 'delete_dentist',
                      'page_title' => 'delete user account',
                      'module_id' => '4',
                      'link_icon' => '',
                      'order' => '105',
                      'table_name' => 'dentists',
                      'func_action' => 'delete',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'show disease details',
                      'function_description' => 'show disease details',
                      'slugs' => 'show-disease',
                      'name_on_class' => 'show_disease',
                      'page_title' => 'disease details',
                      'module_id' => '4',
                       'link_icon' => '',
                      'order' => '901',
                      'table_name' => 'diseases',
                      'func_action' => 'show',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'create disease account',
                      'function_description' => 'create disease account',
                      'slugs' => 'add-disease',
                      'name_on_class' => 'add_disease',
                      'page_title' => 'create a disease account',
                      'module_id' => '4',
                      'link_icon' => '',
                      'order' => '902',
                      'table_name' => 'diseases',
                      'func_action' => 'add',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'list of diseases',
                      'function_description' => 'list of diseases',
                      'slugs' => 'list-disease',
                      'name_on_class' => 'index',
                      'page_title' => 'list of diseases',
                      'module_id' => '4',
                      'link_icon' => '<i class="fas fa-users"></i>',
                      'order' => '903',
                      'table_name' => 'diseases',
                      'func_action' => 'link',
                      'func_type' => 1,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'edit disease account',
                      'function_description' => 'edit disease account',
                      'slugs' => 'edit-disease',
                      'name_on_class' => 'edit_disease',
                      'page_title' => 'edit disease account',
                      'module_id' => '4',
                      'link_icon' => '',
                      'order' => '904',
                      'table_name' => 'diseases',
                      'func_action' => 'edit',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'delete disease account',
                      'function_description' => 'delete disease account',
                      'slugs' => 'delete-disease',
                      'name_on_class' => 'delete_disease',
                      'page_title' => 'delete disease account',
                      'module_id' => '4',
                      'link_icon' => '',
                      'order' => '905',
                      'table_name' => 'diseases',
                      'func_action' => 'delete',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'show procedure details',
                      'function_description' => 'show procedure details',
                      'slugs' => 'show-procedure',
                      'name_on_class' => 'show_procedure',
                      'page_title' => 'procedure details',
                      'module_id' => '4',
                       'link_icon' => '',
                      'order' => '701',
                      'table_name' => 'dental-procedures',
                      'func_action' => 'show',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'create procedure',
                      'function_description' => 'create procedure',
                      'slugs' => 'add-procedure',
                      'name_on_class' => 'add_procedure',
                      'page_title' => 'create procedure',
                      'module_id' => '4',
                      'link_icon' => '',
                      'order' => '702',
                      'table_name' => 'dental-procedures',
                      'func_action' => 'add',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'list of procedures',
                      'function_description' => 'list of procedures',
                      'slugs' => 'list-procedure',
                      'name_on_class' => 'index',
                      'page_title' => 'list of procedures',
                      'module_id' => '4',
                      'link_icon' => '<i class="fas fa-users"></i>',
                      'order' => '703',
                      'table_name' => 'dental-procedures',
                      'func_action' => 'link',
                      'func_type' => 1,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'edit procedure',
                      'function_description' => 'edit procedure',
                      'slugs' => 'edit-procedure',
                      'name_on_class' => 'edit_procedure',
                      'page_title' => 'edit procedure',
                      'module_id' => '4',
                      'link_icon' => '',
                      'order' => '704',
                      'table_name' => 'dental-procedures',
                      'func_action' => 'edit',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'delete procedure',
                      'function_description' => 'delete procedure',
                      'slugs' => 'delete-procedure',
                      'name_on_class' => 'delete_procedure',
                      'page_title' => 'delete procedure',
                      'module_id' => '4',
                      'link_icon' => '',
                      'order' => '705',
                      'table_name' => 'dental-procedures',
                      'func_action' => 'delete',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'show dental condition details',
                      'function_description' => 'show dental condition detials',
                      'slugs' => 'show-dentalcondition-details',
                      'name_on_class' => 'show_dental_condition_details',
                      'page_title' => 'dental_condition details',
                      'module_id' => '4',
                      'link_icon' => '',
                      'order' => '401',
                      'table_name' => 'dental_conditions',
                      'func_action' => 'show',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'create dental condition',
                      'function_description' => 'create dental condition',
                      'slugs' => 'add-dentalcondition',
                      'name_on_class' => 'add_dental_condition',
                      'page_title' => 'create dental_condition',
                      'module_id' => '4',
                      'link_icon' => '',
                      'order' => '402',
                      'table_name' => 'dental_conditions',
                      'func_action' => 'add',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'list of dental conditions',
                      'function_description' => 'list of dental conditions',
                      'slugs' => 'list-dentalcondition',
                      'name_on_class' => 'index',
                      'page_title' => 'list of dental_conditions',
                      'module_id' => '4',
                      'link_icon' => '<i class="fas fa-user-tag"></i>',
                      'order' => '403',
                      'table_name' => 'dental_conditions',
                      'func_action' => 'link',
                      'func_type' => 1,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'edit dental condition',
                      'function_description' => 'edit dental condition',
                      'slugs' => 'edit-dentalcondition',
                      'name_on_class' => 'edit_dental_condition',
                      'page_title' => 'edit dental_condition',
                      'module_id' => '4',
                      'link_icon' => '',
                      'order' => '404',
                      'table_name' => 'dental_conditions',
                      'func_action' => 'edit',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'delete dental condition',
                      'function_description' => 'delete dental condition',
                      'slugs' => 'delete-dentalcondition',
                      'name_on_class' => 'delete_dental_condition',
                      'page_title' => 'delete dental_condition',
                      'module_id' => '4',
                      'link_icon' => '',
                      'order' => '405',
                      'table_name' => 'dental_conditions',
                      'func_action' => 'delete',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'show medicine allergies details',
                      'function_description' => 'show medicine allergies details',
                      'slugs' => 'show-medicine-allergies',
                      'name_on_class' => 'show_medicine_allergies',
                      'page_title' => 'medicine allergies details',
                      'module_id' => '4',
                       'link_icon' => '',
                      'order' => '801',
                      'table_name' => 'medicine_allergies',
                      'func_action' => 'show',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'create medicine allergies',
                      'function_description' => 'create medicine allergies',
                      'slugs' => 'add-medicine-allergies',
                      'name_on_class' => 'add_medicine_allergies',
                      'page_title' => 'create a medicine allergies',
                      'module_id' => '4',
                      'link_icon' => '',
                      'order' => '802',
                      'table_name' => 'medicine_allergies',
                      'func_action' => 'add',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'list of medicine allergies',
                      'function_description' => 'list of medicine allergies',
                      'slugs' => 'list-medicine-allergies',
                      'name_on_class' => 'list_medicine_allergies',
                      'page_title' => 'list of medicine allergies',
                      'module_id' => '4',
                      'link_icon' => '<i class="fas fa-users"></i>',
                      'order' => '803',
                      'table_name' => 'medicine_allergies',
                      'func_action' => 'link',
                      'func_type' => 1,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'edit medicine allergies account',
                      'function_description' => 'edit medicine allergies account',
                      'slugs' => 'edit-medicine-allergies',
                      'name_on_class' => 'edit_medicine_allergies',
                      'page_title' => 'edit medicine allergies account',
                      'module_id' => '4',
                      'link_icon' => '',
                      'order' => '804',
                      'table_name' => 'medicine_allergies',
                      'func_action' => 'edit',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'delete medicine allergies account',
                      'function_description' => 'delete medicine allergies account',
                      'slugs' => 'delete-medicine-allergies',
                      'name_on_class' => 'delete_medicine_allergies',
                      'page_title' => 'delete medicine allergies account',
                      'module_id' => '4',
                      'link_icon' => '',
                      'order' => '805',
                      'table_name' => 'medicine_allergies',
                      'func_action' => 'delete',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],

                ];
                //print_r($data); die();
                $db      = \Config\Database::connect();
                $builder = $db->table($this->table);
                $builder->insertBatch($data);
        }
}
