<?php namespace App\Database\Seeds;

class PermissionInventorySeeder extends \CodeIgniter\Database\Seeder
{
        public $table = 'permissions';

        public function run()
        {
                $data = [
                  [
                      'function_name' => 'show medicine details',
                      'function_description' => 'show medicine details',
                      'slugs' => 'show-medicine',
                      'name_on_class' => 'show_medicine',
                      'page_title' => 'medicine details',
                      'module_id' => '3',
                       'link_icon' => '',
                      'order' => '301',
                      'table_name' => 'medicines',
                      'func_action' => 'show',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'create medicine',
                      'function_description' => 'create medicine',
                      'slugs' => 'add-medicine',
                      'name_on_class' => 'add_medicine',
                      'page_title' => 'create a medicine',
                      'module_id' => '3',
                      'link_icon' => '',
                      'order' => '302',
                      'table_name' => 'medicines',
                      'func_action' => 'add',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'list of medicines',
                      'function_description' => 'list of medicines',
                      'slugs' => 'list-medicine',
                      'name_on_class' => 'index',
                      'page_title' => 'list of medicines',
                      'module_id' => '3',
                      'link_icon' => '<i class="fas fa-users"></i>',
                      'order' => '303',
                      'table_name' => 'medicines',
                      'func_action' => 'link',
                      'func_type' => 1,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'edit medicine',
                      'function_description' => 'edit medicine',
                      'slugs' => 'edit-medicine',
                      'name_on_class' => 'edit_medicine',
                      'page_title' => 'edit medicine',
                      'module_id' => '3',
                      'link_icon' => '',
                      'order' => '304',
                      'table_name' => 'medicines',
                      'func_action' => 'edit',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'delete medicine',
                      'function_description' => 'delete medicine',
                      'slugs' => 'delete-medicine',
                      'name_on_class' => 'delete_medicine',
                      'page_title' => 'delete medicine',
                      'module_id' => '3',
                      'link_icon' => '',
                      'order' => '305',
                      'table_name' => 'medicines',
                      'func_action' => 'delete',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'show medicine_stock details',
                      'function_description' => 'show medicine_stock details',
                      'slugs' => 'show_medicine_stock',
                      'name_on_class' => 'show_medicine_stock',
                      'page_title' => 'Medicine-Stocks details',
                      'module_id' => '3',
                       'link_icon' => '',
                      'order' => '501',
                      'table_name' => 'medicine-stocks',
                      'func_action' => 'show',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'create medicine_stock account',
                      'function_description' => 'create medicine_stock account',
                      'slugs' => 'add_medicine_stock',
                      'name_on_class' => 'add_medicine_stock',
                      'page_title' => 'create a medicine-stock account',
                      'module_id' => '3',
                      'link_icon' => '',
                      'order' => '502',
                      'table_name' => 'medicine-stocks',
                      'func_action' => 'add',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'list of medicine-stocks',
                      'function_description' => 'list of medicine-stock',
                      'slugs' => 'list_medicine_stock',
                      'name_on_class' => 'index',
                      'page_title' => 'list of medicine-stocks',
                      'module_id' => '3',
                      'link_icon' => '<i class="fas fa-users"></i>',
                      'order' => '503',
                      'table_name' => 'medicine-stocks',
                      'func_action' => 'link',
                      'func_type' => 1,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'edit medicine-stock account',
                      'function_description' => 'edit medicine-stock account',
                      'slugs' => 'edit_medicine_stock',
                      'name_on_class' => 'edit_medicine_stock',
                      'page_title' => 'edit medicine-stock account',
                      'module_id' => '3',
                      'link_icon' => '',
                      'order' => '504',
                      'table_name' => 'medicine-stocks',
                      'func_action' => 'edit',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'delete medicine-stock account',
                      'function_description' => 'delete medicine-stock account',
                      'slugs' => 'delete-medstock',
                      'name_on_class' => 'delete_medicine_stock',
                      'page_title' => 'delete medstock account',
                      'module_id' => '3',
                      'link_icon' => '',
                      'order' => '505',
                      'table_name' => 'medicine-stocks',
                      'func_action' => 'delete',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'show supplies details',
                      'function_description' => 'show supplies details',
                      'slugs' => 'show-supplies',
                      'name_on_class' => 'show_supplies',
                      'page_title' => 'supplies details',
                      'module_id' => '3',
                       'link_icon' => '',
                      'order' => '601',
                      'table_name' => 'supplies',
                      'func_action' => 'show',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'create supplies',
                      'function_description' => 'create supplies',
                      'slugs' => 'add-supplies',
                      'name_on_class' => 'add_supplies',
                      'page_title' => 'create supplies',
                      'module_id' => '3',
                      'link_icon' => '',
                      'order' => '602',
                      'table_name' => 'supplies',
                      'func_action' => 'add',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'list of supplies',
                      'function_description' => 'list of supplies',
                      'slugs' => 'list-supplies',
                      'name_on_class' => 'index',
                      'page_title' => 'list of supplies',
                      'module_id' => '3',
                      'link_icon' => '<i class="fas fa-users"></i>',
                      'order' => '603',
                      'table_name' => 'supplies',
                      'func_action' => 'link',
                      'func_type' => 1,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'edit supplies',
                      'function_description' => 'edit supplies',
                      'slugs' => 'edit-supplies',
                      'name_on_class' => 'edit_supplies',
                      'page_title' => 'edit supplies',
                      'module_id' => '3',
                      'link_icon' => '',
                      'order' => '604',
                      'table_name' => 'supplies',
                      'func_action' => 'edit',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'delete supplies',
                      'function_description' => 'delete supplies',
                      'slugs' => 'delete-supplies',
                      'name_on_class' => 'delete_supplies',
                      'page_title' => 'delete supplies',
                      'module_id' => '3',
                      'link_icon' => '',
                      'order' => '605',
                      'table_name' => 'supplies',
                      'func_action' => 'delete',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'show supply stocks details',
                      'function_description' => 'show supply stocks details',
                      'slugs' => 'show-supply-stocks',
                      'name_on_class' => 'show_supply_stocks',
                      'page_title' => 'supply stocks details',
                      'module_id' => '3',
                      'link_icon' => '',
                      'order' => '201',
                      'table_name' => 'supply_stocks',
                      'func_action' => 'show',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'create supply stocks account',
                      'function_description' => 'create supply stocks account',
                      'slugs' => 'add-supply-stocks',
                      'name_on_class' => 'add_supply_stocks',
                      'page_title' => 'create a supply stocks account',
                      'module_id' => '3',
                      'link_icon' => '',
                      'order' => '202',
                      'table_name' => 'supply_stocks',
                      'func_action' => 'add',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'list of supply stocks',
                      'function_description' => 'list of supply stocks',
                      'slugs' => 'list-supply-stocks',
                      'name_on_class' => 'index',
                      'page_title' => 'list of supply stocks',
                      'module_id' => '3',
                      'link_icon' => '<i class="fas fa-boxes"></i>',
                      'order' => '203',
                      'table_name' => 'supply_stocks',
                      'func_action' => 'link',
                      'func_type' => 1,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'edit supply stocks account',
                      'function_description' => 'edit supply stocks account',
                      'slugs' => 'edit-supply-stocks',
                      'name_on_class' => 'edit_supply_stocks',
                      'page_title' => 'edit supply stocks account',
                      'module_id' => '3',
                      'link_icon' => '',
                      'order' => '204',
                      'table_name' => 'supply_stocks',
                      'func_action' => 'edit',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                      'function_name' => 'delete supply stocks account',
                      'function_description' => 'delete supply stocks account',
                      'slugs' => 'delete-supply-stocks',
                      'name_on_class' => 'delete_supply_stocks',
                      'page_title' => 'delete supply stocks account',
                      'module_id' => '3',
                      'link_icon' => '',
                      'order' => '205',
                      'table_name' => 'supply_stocks',
                      'func_action' => 'delete',
                      'func_type' => 3,
                      'allowed_roles' => "[1]",
                      'status' => 'a',
                      'created_at' => date('Y-m-d H:i:s')
                  ],
                ];
                //print_r($data); die();
                $db      = \Config\Database::connect();
                $builder = $db->table($this->table);
                $builder->insertBatch($data);
        }
}
